### ISSUE TITLE
Build telemetry failure makes build fail

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#4049]
If the build telemetry task fails it causes the whole build to fail, this doesn't look desirable.

We set `ContinueOnError` but doesn't seems to have the desired effect 

https://github.com/icerpc/icerpc-csharp/blob/9edecc0ccaddee829828f2da64ce150b692d340f/tools/IceRpc.Slice.Tools/IceRpc.Slice.Tools.targets#L84

I guess this can be because warning as errors in our builds...

We can also consider providing some logging for this task, currently it doesn't emit any logs

```
Restore complete (0.2s)
    Determining projects to restore...
    All projects are up-to-date for restore.
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  Interop.Tests succeeded with 1 warning(s) (0.5s) → tests/Interop.Tests/bin/Debug/net8.0/Interop.Tests.dll
    /Users/bernard/.nuget/packages/icerpc.slice.tools/0.4.0-preview1/build/IceRpc.Slice.Tools.targets(76,5): warning MSB6006: "dotnet" exited with code 1.
```

**Comment by externl** [comment]
Do we know why the telemetry task is failing?

**Comment by pepone** [comment]
In this case the working directory was not correctly set with the new package, see #4048

**Comment by bernardnormier** [comment]
It would be good to provide some diagnostic on warning/error. Otherwise, you have no idea what's wrong and that you need to (for example) disable build telemetry to get a clean build.

**Comment by bernardnormier** [comment]
Fixed by #4054.

**Comment by InsertCreativityHere** [comment]
This isn't completely solved yet.
If the JSON parsing of the telemetry data (from `slicec-cs`) fails, then it causes the whole build to fail.

Specifically, I intentionally added an extra comma in the middle of the JSON output in `main.rs`.
So, I don't think this is a realistic problem, and no, we shouldn't guard against "we broke slicec-cs".

All I'm saying is that some runtime errors in the build telemetry still cause the build to fail.
And if this random JSON parsing error causes that, I'm sure that there are still others too.

```
PS D:\Code\Workspace\icerpc-csharp> .\build.cmd

//...
// building the Rust crate
//...

dotnet build -nr:false  --configuration Debug
Restore complete (1.4s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  IceRpc.Slice.Tools succeeded (1.3s) → IceRpc.Slice.Tools\bin\Debug\netstandard2.0\IceRpc.Slice.Tools.dll
  IceRpc.ProtocGen succeeded (1.8s) → IceRpc.ProtocGen\bin\Debug\net8.0\IceRpc.ProtocGen.dll
  IceRpc.Protobuf.Tools succeeded (1.9s) → IceRpc.Protobuf.Tools\bin\Debug\netstandard2.0\IceRpc.Protobuf.Tools.dll

Build succeeded in 3.5s
dotnet build -nr:false  --configuration Debug
Restore complete (2.2s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  IceRpc.Extensions.DependencyInjection                                                     ResolvePackageAssets (0.1s)
  IceRpc.Slice.Generators succeeded (1.3s) → src\IceRpc.Slice.Generators\bin\Debug\netstandard2.0\IceRpc.Slice.Generators.dll
  IceRpc.Protobuf.Generators succeeded (1.2s) → src\IceRpc.Protobuf.Generators\bin\Debug\netstandard2.0\IceRpc.Protobuf.Generators.dll
  ZeroC.Slice succeeded (2.3s) → src\ZeroC.Slice\bin\Debug\net8.0\ZeroC.Slice.dll
  IceRpc failed with 1 error(s) (1.2s)
    D:\Code\Workspace\icerpc-csharp\tools\IceRpc.Slice.Tools\IceRpc.Slice.Tools.targets(56,5): error MSB4018:
      The "SliceCCSharpTask" task failed unexpectedly.
      System.Text.Json.JsonException: ',' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 77.
       ---> System.Text.Json.JsonReaderException: ',' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 77.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
         at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
         at IceRpc.Slice.Tools.SliceCCSharpTask.LogEventsFromTextOutput(String singleLine, MessageImportance messageImportance) in D:\Code\Workspace\icerpc-csharp\tools\IceRpc.Slice.Tools\SliceCCSharpTask.cs:line 140
         at Microsoft.Build.Utilities.ToolTask.LogMessagesFromStandardErrorOrOutput(Queue dataQueue, ManualResetEvent dataAvailableSignal, MessageImportance messageImportance, StandardOutputOrErrorQueueType queueType)
         at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
         at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
         at Microsoft.Build.Utilities.ToolTask.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)                                                                                                                                                                                                                                                      
Build failed with 1 error(s) in 6.1s
PS D:\Code\Workspace\icerpc-csharp>
```

**Comment by pepone** [comment]
> If the JSON parsing of the telemetry data (from slicec-cs) fails, then it causes the whole build to fail.

If that happens it is a bug in slicec-cs. And you can workaround by disabling build telemetry, I don't think we should handle this exceptions.

**Comment by InsertCreativityHere** [comment]
I agree that we shouldn't specifically handle these exceptions, but I thought that what we were going for was that a build-telemetry failure shouldn't cause the whole build to fail. This was just the easiest test case I could think up.

> If the build telemetry task fails it causes the whole build to fail, this doesn't look desirable.

If I misunderstood what the goal was, and we're fine with some failures cascading into whole-build-failures, feel free to re-close this.

**Comment by InsertCreativityHere** [comment]
Nevermind, this isn't an issue with the build telemetry.
It just happens that we parse the telemetry output in a separate tool before we call into the telemetry reporter.
And that tool (correctly) expects all of `slicec-cs`'s output to be valid JSON.
